'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),src=fs.readFileSync(path.join(root,'js/public-empire.js'),'utf8');
const defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{resolve,promise};};
const league=(id,extra={})=>({id,league_id:id,season:'2026',status:'in_season',total_rosters:2,settings:{type:2,draft_rounds:2},roster_positions:['QB'],scoring_settings:{pass_td:4},rosters:[{roster_id:1,owner_id:'u'+id,players:['p'+id],settings:{wins:0,losses:0}},{roster_id:2,owner_id:'other'+id,players:[],settings:{wins:0,losses:0}}],users:[],myRosterId:1,...extra});
function fixture(){const store={fw_session_v1:'A'},calls=[],assessments=[],progress=[],writes=[];let held=null,failed=null;const ctx={console,Map,Set,WeakMap,Date,Promise,setTimeout,clearTimeout,AbortController,localStorage:{getItem:k=>store[k]??null,setItem:(k,v)=>{writes.push(k);store[k]=v;}},addEventListener:()=>{},S:{currentLeagueId:'active',rosters:[{roster_id:1,players:['active']}],playerStats:{sentinel:true}},App:{LI_LOADED:true,LI:{playerScores:{p111:100,p222:200}},fetchAllPlayers:async()=>({p111:{full_name:'A',position:'QB'},p222:{full_name:'B',position:'QB'}}),calcRawPts:(row,sc)=>Object.entries(sc).reduce((n,[k,v])=>n+(Number(row[k])||0)*v,0),assessAllTeams:(rs,players,stats,l)=>{assessments.push({rs,stats,l});return rs.map(r=>({rosterId:r.roster_id,healthScore:50,tier:'CROSSROADS'}));},buildEmpireDna:(saved,txns)=>({...saved,tradeCount:txns.length})}};ctx.window=ctx;ctx.getOwnerIdentity=()=>({userId:'A',username:null});ctx.fetchSeasonStats=async y=>{calls.push('stats:'+y);return {'p111':{gp:2,pass_td:5},'p222':{gp:2,pass_td:2}};};ctx.fetch=async url=>{calls.push(url);if(held)return held(url);if(failed&&url.includes(failed))return{ok:false,status:503};return{ok:true,json:async()=>url.endsWith('/state/nfl')?{season:'2026',season_type:'regular',week:3}:[]};};ctx.OD={getSessionToken:()=> 'fixture-token',getAppSession:()=>({user:{id:'A'}}),getClient:()=>({from:table=>{calls.push(table);const q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:{dna_map:{x:'STALWART'}}})};return q;}})};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(root,'js/public-portfolio.js'),'utf8'),ctx);vm.runInContext(src,ctx);ctx.App.loadLeagueIntelContext=async({state})=>({leagueId:state.currentLeagueId,season:state.season,data:{playerScores:{p111:Number(state.currentLeagueId),p222:Number(state.currentLeagueId)*2}}});ctx.App.assessAllTeamsWithContext=(...args)=>ctx.App.assessAllTeams(...args);ctx.App.TradePickInventory={load:async l=>{calls.push('picks:'+l.id);return{status:'ready',league:{...l,drafts:[]},tradedPicks:[]};},inventory:l=>({status:'ready',coverage:{complete:true,format:'dynasty'},byOwner:{[l.rosters[0].owner_id]:[{year:2027,round:1,fromRosterId:1}]},league:l}),owns:()=>true,priced:()=>true,pickId:p=>JSON.stringify(p)};return{ctx,store,calls,assessments,progress,writes,setHeld:f=>held=f,setFail:v=>failed=v,run:opts=>ctx.App.PublicEmpire.load({leagues:[league('111'),league('222')],identity:ctx.App.PublicPortfolio.capture(),onProgress:s=>progress.push(s),...opts})};}
const tests={
async unverifiedLegacyDisplayNameCannotSelectCloudNotes(){const x=fixture();x.ctx.getOwnerIdentity=()=>({userId:null,username:null});x.ctx.OD.getAppSession=()=>null;x.ctx.getCurrentUsername=()=> 'other-account';const out=await x.run({leagues:[league('111')]});assert(!x.calls.includes('owner_dna'),'unverified display metadata must not select a cloud principal');assert.equal(out.leagues[0].empireEvidence.dna.savedNotes,'unavailable');},
async pendingAndUnknownTradesCannotBecomeOwnerReads(){
 const x=fixture(),babel=require('@babel/standalone'),text=fs.readFileSync(path.join(root,'js/tabs/global-view.js'),'utf8');
 babel.packages.traverse.default(babel.packages.parser.parse(text,{sourceType:'script',plugins:['jsx']}),{FunctionDeclaration(p){if(['inferDnaFromTransactions','buildEmpireDna'].includes(p.node.id?.name))vm.runInContext(text.slice(p.node.start,p.node.end),x.ctx);}});
 x.ctx.App.buildEmpireDna=x.ctx.buildEmpireDna;
 const rows=[1,2].map(n=>({transaction_id:String(n),type:'trade',status:'pending',roster_ids:[1,2],draft_picks:[{owner_id:2,previous_owner_id:1}]}));
 x.ctx.fetch=async url=>({ok:true,json:async()=>url.endsWith('/transactions/1')?rows:[]});
 const out=await x.run({leagues:[league('111')]});
 assert.equal(out.leagues[0].empireDna.other111,undefined,'pending offers must not classify an owner as a completed-trade seller');
 for(const status of ['pending','failed','unrecognized',undefined]) assert.equal(x.ctx.inferDnaFromTransactions(rows.map(r=>({...r,status})),league('111').rosters).other111,undefined);
 assert.equal(x.ctx.inferDnaFromTransactions(rows.map(r=>({...r,status:'complete'})),league('111').rosters).other111,'ACCEPTOR','completed pick acquisitions retain established behavior');
},
async malformedWeeklyHistoryCannotBeCertifiedComplete(){for(const rows of [[null],[{type:'trade'}]]){const x=fixture();x.ctx.fetch=async url=>({ok:true,json:async()=>url.endsWith('/transactions/1')?rows:[]});const out=await x.run({leagues:[league('111')]});assert.equal(out.leagues[0].empireEvidence.transactions.status,'unavailable');assert.equal(out.leagues[0].empireDna.tradeCount,0);}},
async sameRosterIdsStayInTheirLeagueAndGlobalsUntouched(){const x=fixture(),before=JSON.stringify(x.ctx.S),result=await x.run();assert.equal(JSON.stringify(x.ctx.S),before);assert.equal(x.writes.length,0);assert.equal(x.assessments.length,2);assert.equal(x.assessments[0].rs[0].players[0],'p111');assert.equal(x.assessments[1].rs[0].players[0],'p222');assert.equal(x.assessments[0].stats.p111.seasonAvg,10);assert.equal(result.leagues[1].empireEvidence.stats.season,'2026');assert.equal(x.calls.filter(c=>c==='stats:2026').length,1);},
async malformedStatsAndOutageNeverInventHistoricalProduction(){for(const value of [[],null]){const x=fixture();x.ctx.fetchSeasonStats=async()=>value;const r=await x.run({leagues:[league('111')]});assert.equal(r.leagues[0].empireEvidence.stats.status,'unavailable');assert.equal(x.assessments.length,0);}const x=fixture();x.ctx.fetchSeasonStats=async()=>{throw Error('outage');};const r=await x.run({leagues:[league('111')]});assert.equal(r.leagues[0].empireEvidence.stats.status,'unavailable');assert.equal(x.assessments.length,0);},
async explicitEmptyCurrentSeasonLabelsHistoricalBasis(){const x=fixture();x.ctx.fetchSeasonStats=async y=>y==='2026'?{}:{p111:{gp:4,pass_td:5}};const r=await x.run({leagues:[league('111')]});assert.equal(r.leagues[0].empireEvidence.stats.status,'historical');assert.equal(r.leagues[0].empireEvidence.stats.season,'2025');assert.equal(x.assessments[0].stats.p111.prevAvg,5);assert.equal(x.assessments[0].stats.p111.seasonAvg,undefined);},
async missingPlayersAndStaleCardsDoNotProduceReads(){for(const patch of [{rosters:[{roster_id:1,owner_id:'u111'}]},{_portfolioStale:true}]){const x=fixture(),r=await x.run({leagues:[league('111',patch)]});assert.equal(r.leagues[0].empireEvidence.picks.status,'unavailable');assert.equal(r.leagues[0].empireAssessments.length,0);}},
async pickFailureIsNotEmptyOrAssessedAndRetryRecovers(){const x=fixture();x.ctx.App.TradePickInventory.load=async()=>{throw Error('503');};const r=await x.run({leagues:[league('111')]});assert.equal(r.leagues[0].tradedPicks,undefined);assert.equal(r.leagues[0].empireEvidence.picks.status,'unavailable');assert.equal(r.leagues[0].empireAssessments.length,0);},
async nonSleeperNeverUsesSleeperTransactionsAndPreservesStatus(){const x=fixture(),status={provider:'espn',leagueId:'espn_7_2026',season:'2026',status:'stale',scope:'trades',lastSuccessAt:3};const r=await x.run({leagues:[league('espn_7_2026',{_espn:true,transactionStatus:status,transactions:[{type:'trade'}]})]});assert(!x.calls.some(c=>c.includes('api.sleeper.app')));assert.equal(r.leagues[0].empireEvidence.transactions.status,'stale');assert.equal(r.leagues[0].empireEvidence.dna.transactions,'unavailable');assert.equal(x.assessments.length,0);},
async accountChangeDuringPlayersStopsEveryFollowup(){const x=fixture(),d=defer();x.ctx.App.fetchAllPlayers=()=>d.promise;const work=x.run();x.store.fw_session_v1='B';d.resolve({p111:{full_name:'A'}});await assert.rejects(work,/context changed/);assert.equal(x.calls.length,0);assert.equal(x.progress.length,1);},
async accountChangeDuringSavedNotesStopsTransactionsAndWrites(){const x=fixture(),d=defer();x.ctx.OD.getClient=()=>({from:()=>{const q={select:()=>q,eq:()=>q,maybeSingle:()=>d.promise};return q;}});const work=x.run({leagues:[league('111')]});await new Promise(r=>setTimeout(r,0));x.store.fw_session_v1='B';const n=x.progress.length;d.resolve({data:{dna_map:{secret:'A'}}});await assert.rejects(work,/context changed/);assert.equal(x.progress.length,n);assert(!x.calls.some(c=>c.includes('transactions')));assert.equal(x.writes.length,0);},
async transactionFailureRemainsUnavailableAndNoPartialInference(){const x=fixture();x.setFail('/transactions/3');const r=await x.run({leagues:[league('111')]});assert.equal(r.leagues[0].empireEvidence.dna.transactions,'unavailable');assert.equal(r.leagues[0].empireEvidence.transactions.status,'unavailable');assert.equal(r.leagues[0].empireDna.tradeCount,0);assert.equal(x.calls.filter(c=>c.includes('transactions')).length,4);},
async supersededGenerationCannotPublishOrFollowup(){const x=fixture(),d=defer();let current=true;x.ctx.App.TradePickInventory.load=()=>d.promise;const work=x.run({isCurrent:()=>current});await new Promise(r=>setTimeout(r,0));current=false;d.resolve({status:'ready',league:league('111'),tradedPicks:[]});await assert.rejects(work,/context changed/);assert(!x.calls.some(c=>c.startsWith('stats:')));},
async boundedTimeoutAndNoColdGlobalEngineInvocation(){const x=fixture();x.ctx.App.fetchAllPlayers=()=>new Promise(()=>{});x.ctx.App.loadLeagueIntel=()=>{throw Error('must not call global engine');};const r=await x.run({leagues:[],timeoutMs:5});assert.equal(r.status.players.status,'unavailable');},
async actualReviewedAdapterHonorsConsumedAndTransferredRights(){
 const x=fixture(),shared=process.env.EMPIRE_SHARED_SOURCE||'/Users/jacobc/Projects/dhq-shared-readiness-actual-capital',adapter=process.env.EMPIRE_TRADE_SOURCE||'/Users/jacobc/Projects/warroom-readiness-public-trade-picks/js/trade-pick-inventory.js';
 vm.runInContext(fs.readFileSync(path.join(shared,'team-assess.js'),'utf8'),x.ctx);vm.runInContext(fs.readFileSync(adapter,'utf8'),x.ctx);
 const raw=league('111',{status:'drafting'});let fail=false;
 x.ctx.fetch=async url=>{if(fail&&url.endsWith('/traded_picks'))return{ok:false,status:503};const data=url.endsWith('/traded_picks')?[{season:'2026',round:1,roster_id:1,owner_id:2,previous_owner_id:1},{season:'2027',round:2,roster_id:2,owner_id:1,previous_owner_id:2}]:url.endsWith('/drafts')?[{draft_id:'777',league_id:'111',season:'2026'}]:url.endsWith('/draft/777')?{draft_id:'777',league_id:'111',season:'2026',status:'drafting',settings:{rounds:2,teams:2,player_type:1},slot_to_roster_id:{1:1,2:2}}:url.endsWith('/draft/777/picks')?[{pick_no:1,round:1,draft_slot:1,roster_id:2,player_id:'p222'}]:[];return{ok:true,json:async()=>data};};
 const result=await x.run({leagues:[raw]});const state=result.leagues[0].empirePickState;assert.equal(state.coverage.complete,true,JSON.stringify(state.coverage));const rights=state.byOwner.u111;assert.equal(rights.length,6);assert(!rights.some(p=>p.year===2026&&p.round===1));assert(rights.some(p=>p.year===2027&&p.round===2&&p.fromRosterId==='2'));assert.equal(raw.tradedPicks,undefined,'caller input must not mutate');
 fail=true;const failed=await x.run({leagues:[raw]});assert.equal(failed.leagues[0].empireEvidence.picks.status,'unavailable');assert.equal(failed.leagues[0].empirePickState,null);fail=false;assert.equal((await x.run({leagues:[raw]})).leagues[0].empireEvidence.picks.status,'ready');
},
async actualAppBootstrapCancelsAtModuleAndPendingEvidenceBoundaries(){
 const x=fixture(),babel=require('@babel/standalone'),text=fs.readFileSync(path.join(root,'js/app.js'),'utf8');let callback;
 babel.packages.traverse.default(babel.packages.parser.parse(text,{sourceType:'script',plugins:['jsx']}),{CallExpression(p){if(p.node.callee.name==='useEffect'&&text.slice(p.node.start,p.node.end).includes('window.App.PublicEmpire.load'))callback=text.slice(p.node.arguments[0].start,p.node.arguments[0].end);}});
 const d=defer();let cleared=0,published=0;x.ctx.wrLoadModuleGroup=()=>d.promise;Object.assign(x.ctx,{proMode:true,selectedLeague:null,portfolioApi:x.ctx.App.PublicPortfolio,portfolioAccount:{current:x.ctx.App.PublicPortfolio.capture()},setEmpireSnapshot:()=>published++,setEmpirePlayers:()=>{},empirePlayers:{},sleeperLeagues:[league('111')],visibleEspnLeagues:[],visibleMflLeagues:[],sleeperUser:{user_id:'900'},clearChangedPortfolio:()=>cleared++});vm.runInContext('('+callback+')()',x.ctx);x.store.fw_session_v1='B';d.resolve();await new Promise(r=>setTimeout(r,0));assert.equal(cleared,1);assert.equal(x.calls.length,0);assert.equal(published,1,'only pending reset before invalidation');
},
async modelRejectsGlobalAssessmentsAndUnverifiedPicks(){const x=fixture(),babel=require('@babel/standalone'),text=fs.readFileSync(path.join(root,'js/tabs/global-view.js'),'utf8');let fn;babel.packages.traverse.default(babel.packages.parser.parse(text,{sourceType:'script',plugins:['jsx']}),{FunctionDeclaration(p){if(p.node.id?.name==='buildEmpirePortfolioModel')fn=text.slice(p.node.start,p.node.end);}});vm.runInContext(fn,x.ctx);const input={allLeagues:[league('111',{rosters:[{roster_id:1,owner_id:'u111',players:['p111']}],empireAssessments:[{rosterId:1,healthScore:100}]})],playersData:{p111:{full_name:'Player',position:'QB'}},scores:{p111:500},assessTeam:()=>{throw Error('global wrong roster');},portfolioCoverage:{listVerified:true,status:'partial',knownCount:2,loadedCount:1}};const r=x.ctx.buildEmpirePortfolioModel(input);assert.equal(r.provinces[0].healthScore,null);assert.equal(r.provinces[0].wins,null);assert.equal(r.picks.length,0);assert.equal(r.pickCapital.complete,false);assert.equal(r.coverage.complete,false);assert.equal(r.totals.totalRecord.wins,null);},
};
module.exports={fixture,league,defer};
if(require.main===module)(async()=>{for(const[name,test]of Object.entries(tests)){await test();console.log('PASS',name);}console.log(Object.keys(tests).length+' Empire evidence groups passed.');})().catch(e=>{console.error(e);process.exitCode=1;});
