'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const file=process.env.READINESS_CONNECT_SOURCE||'connect-sleeper.html';
const script=[...fs.readFileSync(file,'utf8').matchAll(/<script>([\s\S]*?)<\/script>/g)].at(-1)[1];
const jwt=(id,exp=Math.floor(Date.now()/1000)+3600)=>'eyJhbGciOiJIUzI1NiJ9.'+Buffer.from(JSON.stringify({exp,sub:id,app_metadata:{user_id:id,session_version:1}})).toString('base64url')+'.controlled';
const {payloads}=require('./helpers/mfl-caller-fixture.cjs');
const mflSource=fs.readFileSync(process.env.MFL_MODULE_SOURCE||'reconai-shared/mfl-api.js','utf8');
const tick=()=>new Promise(r=>setImmediate(r));
async function finishMfl(s,start=0){for(let n=0;n<5;n++){for(const r of s.requests.slice(start)){if(r.done||!r.options.body)continue;const body=JSON.parse(r.options.body);if(!body.url)continue;const target=new URL(body.url);r.done=true;r.resolve(payloads(target.searchParams.get('L'),target.pathname.split('/')[1])[target.searchParams.get('TYPE')]);}await tick();}}
const A=JSON.stringify({token:jwt('account-a'),user:{id:'account-a'}}), B=JSON.stringify({token:jwt('account-b'),user:{id:'account-b'}});
function storage(seed={}){const data=new Map(Object.entries(seed));return{data,getItem:k=>data.get(k)??null,setItem(k,v){data.set(k,String(v));},removeItem:k=>data.delete(k)};}
function setup(){const elements=new Map(),requests=[],timers=new Map();let timerId=0;const element=id=>{if(!elements.has(id)){const classes=new Set();elements.set(id,{id,value:'',disabled:false,textContent:'',className:'',focus(){},classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x),toggle(x,on){on===undefined?classes.has(x)?classes.delete(x):classes.add(x):on?classes.add(x):classes.delete(x);}}});}return elements.get(id);};const local=storage({fw_session_v1:A}),session=storage();const env={console,crypto:require('node:crypto').webcrypto,App:{CONFIG:{functionsBase:'https://fixture.invalid/functions/v1',supabaseAnon:'fixture-anon'}},addEventListener(){},AbortController,URL,Date,atob,JSON,Object,Array,Number,String,Error,Set,Map,localStorage:local,sessionStorage:session,location:{hostname:'localhost',href:'',replace(url){this.href=url;}},navigator:{userAgent:'Fixture browser'},setTimeout:(fn,ms)=>{timers.set(++timerId,{fn,ms});return timerId;},clearTimeout:id=>timers.delete(id),document:{referrer:'',getElementById:element,addEventListener(){},activeElement:null},fetch(url,options={}){if(url.includes('/analytics_events'))return Promise.resolve({ok:true});return new Promise((resolve,reject)=>{const request={url,options,resolve:data=>resolve({ok:true,status:200,json:async()=>data}),reject};requests.push(request);options.signal?.addEventListener('abort',()=>reject(Object.assign(Error('aborted'),{name:'AbortError'})));});}};env.window=env;vm.createContext(env);vm.runInContext(mflSource,env);vm.runInContext([...fs.readFileSync(file,'utf8').matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1],env);vm.runInContext(script,env);element('enterBtn').disabled=true;element('sleeperName').value='controlled';element('mflLeagueId').value='12345';element('mflYear').value='2026';element('espnLeagueId').value='56789';element('espnYear').value='2026';return{env,element,local,session,requests,timers};}
const valid={user_id:'123456789012345678',username:'Controlled'};
const tests={
 async failedSignOutCanRetry(){const s=setup(),p=s.env.connectSleeper();s.requests[0].resolve(valid);await p;const auth=s.local.getItem('od_auth_v1');s.session.setItem('espn_s2','fixture');const remove=s.session.removeItem;s.session.removeItem=()=>{throw Error('blocked storage');};s.env.signOut();assert.equal(s.local.getItem('fw_session_v1'),A,'Failed cleanup must restore its own removed credential');assert.equal(s.local.getItem('od_auth_v1'),auth);assert.equal(s.env.location.href,'');s.session.removeItem=remove;s.env.signOut();assert.equal(s.env.location.href,'landing.html?signout');},
 async unhealthySessionsCannotConnect(){
  for(const bad of [{token:jwt('account-a',1),user:{id:'account-a'}},{token:jwt('account-a'),user:{id:'account-b'}},{token:'broken',user:{id:'account-a'}}]){
   const s=setup();s.local.setItem('fw_session_v1',JSON.stringify(bad));
   vm.runInContext('pageBinding = readConnectionBinding()',s.env);
   const p=s.env.connectSleeper();assert.equal(s.requests.length,0,'Unhealthy or mismatched session cannot save a provider connection');await p;assert.match(s.element('alert').textContent,/Sign in again/);
  }
 },
 async guestRouting(){
  const head=[...fs.readFileSync('index.html','utf8').matchAll(/<script>([\s\S]*?)<\/script>/g)][0][1];
  for(const [keys,expected] of [[{},'landing.html'],[{wr_guest_v1:'1'},'connect-sleeper.html'],[{wr_guest_v1:'1',espn_league_id:'56789'},''],[{wr_guest_v1:'1',mfl_league_id:'12345'},''],[{wr_guest_v1:'1',od_auth_v1:JSON.stringify({username:'Controlled'})},'']]){
   const store=storage(keys),location={hostname:'public.fixture.invalid',href:'',replace(value){this.href=value;}};
   vm.runInNewContext(head,{localStorage:store,window:{location},Date,JSON});assert.equal(location.href,expected,'Every offered guest platform must reach the same app gate');
  }
 },
 async signOutClearsConnection(){const s=setup(),p=s.env.connectSleeper();s.requests[0].resolve(valid);await p;s.session.setItem('espn_s2','fixture');s.env.signOut();assert.equal(s.local.getItem('fw_session_v1'),null);assert.equal(s.local.getItem('od_auth_v1'),null);assert.equal(s.session.getItem('espn_s2'),null);assert.equal(JSON.parse(s.local.getItem('od_profile_v1')).sleeperUsername,undefined);assert.equal(s.env.location.href,'landing.html?signout');},
 async concurrentPlatforms(){const s=setup(),m=s.env.connectMfl(),p=s.env.connectSleeper();s.requests.find(r=>r.url.includes('api.sleeper')).resolve(valid);await p;await finishMfl(s);await m;assert.equal(s.local.getItem('mfl_league_id'),null,'A changed provider binding needs an explicit retry');assert.match(s.element('alert').textContent,/changed/);assert.equal(JSON.parse(s.local.getItem('od_auth_v1')).username,'Controlled');const retry=s.env.connectMfl();await finishMfl(s);await retry;assert.equal(s.local.getItem('mfl_league_id'),'12345');},
 async changedLegacyBinding(){const s=setup(),p=s.env.connectSleeper();const other=JSON.stringify({username:'Other'});s.local.setItem('od_auth_v1',other);s.requests[0].resolve(valid);await p;assert.equal(s.local.getItem('od_auth_v1'),other);assert.equal(s.local.getItem('od_profile_v1'),null);},
 async duplicateSubmission(){const s=setup(),p=s.env.connectSleeper(),q=s.env.connectSleeper();assert.equal(s.requests.length,1,'Pending provider request must not duplicate');s.requests[0].resolve(valid);await Promise.all([p,q]);},
 async changedAccount(){const s=setup(),p=s.env.connectSleeper();s.local.setItem('fw_session_v1',B);s.requests[0].resolve(valid);await p;assert.equal(s.local.getItem('od_auth_v1'),null,'Late A provider reply must not write a connection into B');assert.equal(s.local.getItem('fw_session_v1'),B);},
 async signedOut(){const s=setup(),p=s.env.connectSleeper();s.local.removeItem('fw_session_v1');s.requests[0].resolve(valid);await p;assert.equal(s.local.getItem('od_auth_v1'),null,'Late reply must not recreate signed-out connection');},
 async malformedIdentity(){const s=setup(),p=s.env.connectSleeper();s.requests[0].resolve({user_id:{wrong:true},username:'Controlled'});await p;assert.equal(s.local.getItem('od_auth_v1'),null,'Malformed provider identity must not be accepted');},
 async saveFailure(){const s=setup(),original=s.local.setItem;s.local.setItem=function(k,v){if(k==='od_profile_v1')throw Error('storage full');return original.call(this,k,v);};const p=s.env.connectSleeper();s.requests[0].resolve(valid);await p;assert.equal(s.local.getItem('od_auth_v1'),null,'Failed profile write must roll back incomplete connection');assert.equal(s.element('enterBtn').disabled,true);assert.match(s.element('alert').textContent,/save|storage/i);},
 async staleSignOut(){const s=setup();s.local.setItem('fw_session_v1',B);s.env.signOut();assert.equal(s.local.getItem('fw_session_v1'),B,'Old page must not sign out B');},
 async requestTimeoutAndRetry(){const s=setup(),p=s.env.connectSleeper();const timer=[...s.timers.values()].find(x=>x.ms===20000);assert(timer,'Provider request must have a real timeout');timer.fn();await p;assert.equal(s.element('btnSleeper').disabled,false);assert.equal(s.element('sleeperName').value,'controlled');const retry=s.env.connectSleeper();s.requests[1].resolve(valid);await retry;assert.equal(JSON.parse(s.local.getItem('od_auth_v1')).sleeperUserId,valid.user_id);},
 async exactMflInput(){const s=setup();s.element('mflLeagueId').value='abc12345';const p=s.env.connectMfl();assert.equal(s.requests.length,0,'Malformed league ID must not silently connect a different ID');await p;},
 async mflFailureThenRetry(){const s=setup(),p=s.env.connectMfl();s.requests[0].reject(Error('offline'));await finishMfl(s,1);await p;assert.equal(s.element('btnMfl').disabled,false);const q=s.env.connectMfl();await finishMfl(s);await q;assert.equal(s.local.getItem('mfl_league_id'),'12345');assert.equal(s.local.getItem('mfl_year'),'2026');},
 async partialEspnCookies(){const s=setup();s.element('espnS2').value='controlled-secret';const p=s.env.connectEspn();assert.equal(s.requests.length,0,'Partial private credentials must not fall through to public lookup');await p;},
 async privateEspn(){const s=setup();s.element('espnS2').value='controlled-s2';s.element('espnSwid').value='controlled-swid';const p=s.env.connectEspn();const req=s.requests[0];assert(req.url.endsWith('/espn-proxy'));assert.equal(JSON.parse(req.options.body).espnS2,'controlled-s2');req.resolve({settings:{name:'Controlled ESPN'},teams:[{id:1}]});await p;assert.equal(s.local.getItem('espn_league_id'),'56789');assert.equal(s.session.getItem('espn_s2'),'controlled-s2');assert.equal(s.local.getItem('espn_s2'),null);},
 async pendingEnterAndLateNavigation(){const s=setup(),p=s.env.connectSleeper();s.requests[0].resolve(valid);await p;const q=s.env.connectMfl();s.env.enterApp();assert(![...s.timers.values()].some(x=>x.ms===700),'Cannot navigate while another connection is pending');await finishMfl(s);await q;s.env.enterApp();const nav=[...s.timers.values()].find(x=>x.ms===700);assert(nav);s.local.setItem('fw_session_v1',B);nav.fn();assert.equal(s.env.location.href,'','Delayed navigation must not act after account changed');},
};
module.exports={setup,finishMfl,tick,A,B};
if(require.main===module)(async()=>{let failed=0;for(const[name,test]of Object.entries(tests)){try{await test();console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.message);}}if(failed)process.exitCode=1;})();
